### ISSUE TITLE
Finalize Assignment 1

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au15#18]

**Comment by jayfo** [comment]
A draft of assignment 1 is now posted. I asked @fiannaca and @milnel2 to urgently review the homework for this Friday. Can everybody take a look at the larger assignment?

https://courses.cs.washington.edu/courses/cse440/15au/assignments/assignment1/

@skawas @kelseymunsell

**Comment by milnel2** [comment]
The larger assignment looks good to me. It's a bummer that FitBit comes first alphabetically in the list of applications. Also might be fun to include one of the energy consumption examples: i.e. Magnifisense (http://homes.cs.washington.edu/~mayank/Papers/MagnifiSense.pdf0

**Comment by fiannaca** [comment]
This all looks good to me. I think we should not allow them to use finance, wellness, health, or mood at all in the first homework though. Otherwise, we are effectively asking for only two ideas rather than three.

**Comment by jayfo** [comment]
@fiannaca I'd like to leave it open for them to have a _good_ idea in one of those spaces.

I think this is related to our other thread, where I required them to do more than the domain (i.e., also do the problem). I agree just saying "health" would be a waste. But I'd be happy to hear if somebody had an actually interesting idea in "health".

**Comment by fiannaca** [comment]
Ah I see. That sounds good to me.

**Comment by jayfo** [comment]
Thanks all. I tweaked this in #36.
