### ISSUE TITLE
Review Course Overview

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au15#26]
I've posted a course overview. It should be set, except for the grading scheme is still flagged as subject to change. I don't foresee us changing that much or at all, but didn't want to set it in stone yet.

Can you look at it:

https://courses.cs.washington.edu/courses/cse440/15au/

Speak up if you see any issues?  Otherwise say it looks good?

@fiannaca @milnel2 @skawas @kelseymunsell

**Comment by milnel2** [comment]
Looks good to me.

**Comment by milnel2** [comment]
Sorry, I'm getting overexcited about resolving the issues!

**Comment by jayfo** [comment]
I wish GitHub had a like button.

**Comment by skawas** [comment]
It looks great!

**Comment by kelseymunsell** [comment]
Looks good to me.

**Comment by fiannaca** [comment]
Looks good!
