### ISSUE TITLE
Need Keynote Conversion

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au15#33]
I just put Katharina's previous lecture slides in the Dropbox, at /lecture_slides/katharina/

They're in Keynote, which is useless to me. Can somebody with a Mac:

1) convert each to PDF, so I can see what they look like
2) also convert each to PPTX, so I can borrow from them

Apologies for asking for both, but (1) will preserve formatting, while (2) lets me re-use the slides.

Who has a Mac?  @milnel2 @kelseymunsell @skawas 

I remember @fiannaca has a Surface?

**Comment by milnel2** [comment]
I'm on it.

**Comment by kelseymunsell** [comment]
I don't have a Mac so I'm useless. :)

**Comment by milnel2** [comment]
Hmm, lies! I don't have Keynote on my mac, but I think I can create the pdfs. If no one else can do it, I can also buy Keynote, but it's $20.

**Comment by milnel2** [comment]
I created all the pdfs, although not sure whether the presentation slides converted correctly.

**Comment by fiannaca** [comment]
Yes, I have a Surface 3

**Comment by skawas** [comment]
I converted the presentations into PPTX. I couldn't open week 12 and 13.  Would you please upload them again @jayfo. 
I also created pdfs with speaker notes.

**Comment by jayfo** [comment]
Thanks all. Sounds like Saba is our Keynote expert this quarter.  ;)

@skawas The zip file that's in the `lecture_slides` directory is what I directly got from Katharina.

Do we need to ask her for something?

**Comment by skawas** [comment]
I get this error when I try to open the presentation files for week 12 and week 13 : “Presentations_Katharina's_section” can’t be opened."  I am wondering if there is any presentation for these weeks, since there is 10 weeks in a quarter. :).

**Comment by jayfo** [comment]
Emailed Katharina.

**Comment by jayfo** [comment]
The missing decks were student presentations. Closing.
