### ISSUE TITLE
Need Mac PDF Check

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au15#35]
I have two processes I can use to PDF my PPTX, and I forget which works well.

One of them last year resulted in PDFs full of pink slides. But only if you were using a Mac. 

And perhaps only if you were using a particular viewer (e.g., the built-in viewer?).

Can @skawas and @milnel2 check out my PDF?

https://courses.cs.washington.edu/courses/cse440/15au/slides/lecture/l01-intro.pdf

View it in your browser, then download and view it locally?

Post whether it looks good, or looks pink and freaky?

**Comment by milnel2** [comment]
Looks neither pink nor freaky on my mac both in the browser and downloaded (opened with preview).
