### ISSUE TITLE
Layout of Project Thumbnails

### ISSUE THREAD

**Issue by jayfo** [uwcse440/web-cse440-au15#99]
Now that we're getting project thumbnails from groups, I see two issues:
- Some are giving us white background thumbnails.
- At least one gave us a thumbnail which isn't 150 x 150.

Can we fix up our formatting to handle this better? Perhaps a border, and fixing the width x height?

Alex, can you take this on?

**Comment by fiannaca** [comment]
Sure. I"ll take a look at it.
